"""Reusable, project-independent publication plot styling."""

from .style import (
    AXIS_LINE_WIDTH,
    DEFAULT_FONT_SIZE,
    DENSE_TICK_FONT_SIZE,
    GRID,
    INK,
    LINE_WIDTH,
    MARKER_EDGE_WIDTH,
    MID_INK,
    PALETTE,
    SMALL_FONT_SIZE,
    TICK_LINE_WIDTH,
    WHITE,
    add_line_outline,
    add_panel_label,
    annotate_heatmap,
    apply_publication_style,
    blend,
    finite_or_zero,
    pastel_diverging_cmap,
    pastel_sequential_cmap,
    save_publication_figure,
    style_axes,
)

__all__ = [
    "AXIS_LINE_WIDTH",
    "DEFAULT_FONT_SIZE",
    "DENSE_TICK_FONT_SIZE",
    "GRID",
    "INK",
    "LINE_WIDTH",
    "MARKER_EDGE_WIDTH",
    "MID_INK",
    "PALETTE",
    "SMALL_FONT_SIZE",
    "TICK_LINE_WIDTH",
    "WHITE",
    "add_line_outline",
    "add_panel_label",
    "annotate_heatmap",
    "apply_publication_style",
    "blend",
    "finite_or_zero",
    "pastel_diverging_cmap",
    "pastel_sequential_cmap",
    "save_publication_figure",
    "style_axes",
]
